# Generated by Django 4.2.6 on 2023-10-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bug_type', models.CharField(choices=[('error', 'Error'), ('new_feature', 'New Feature'), ('other', 'Other')], max_length=100)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('TO DO', 'To Do'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], max_length=20)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
